const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Sin,
		C3.Plugins.Arr,
		C3.Plugins.BinaryData,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Plugins.LocalStorage,
		C3.Plugins.Date,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.Button.Acts.SetBoolInstanceVar,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Button.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetMaxLength,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.TextBox.Acts.SetPlaceholder,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.TextBox.Cnds.IsEnabled,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.先看評論_Event2_Act1,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.JavaScriptInEvents.先看評論_Event23
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{Text: 0},
	{按钮: 0},
	{一確認: 0},
	{二確認: 0},
	{正弦: 0},
	{確認: 0},
	{Array: 0},
	{BinaryData: 0},
	{逆: 0},
	{編號: 0},
	{判定星星: 0},
	{Touch: 0},
	{补间动画: 0},
	{圓: 0},
	{帳號圖: 0},
	{帳號名: 0},
	{評論內容: 0},
	{Sprite2: 0},
	{時間: 0},
	{Browser: 0},
	{填寫評論: 0},
	{帳號名稱: 0},
	{資料狀態: 0},
	{LocalStorage: 0},
	{前往: 0},
	{日期: 0},
	{web_app_url: 0},
	{值: 0},
	{save: 0},
	{台詞: 0},
	{s: 0},
	{名字: 0},
	{評論: 0},
	{星數: 0},
	{back: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Text: class extends self.ITextInstance {},
	按钮: class extends self.IButtonInstance {},
	確認: class extends self.IButtonInstance {},
	Array: class extends self.IArrayInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	判定星星: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	圓: class extends self.ISpriteInstance {},
	帳號圖: class extends self.ITextInstance {},
	帳號名: class extends self.ITextInstance {},
	評論內容: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	時間: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	填寫評論: class extends self.ITextInputInstance {},
	帳號名稱: class extends self.ITextInputInstance {},
	資料狀態: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	前往: class extends self.IButtonInstance {},
	日期: class extends self.IInstance {}
}